### PR TITLE
improve Goodreads relay(search) route

### PR DESCRIPTION
**Pull request by gskumawat0**
change post method to get(we are not saving anything to database)
remove immediately invoked functions, instead make cb function asyncronous
improve error handling with try catch
change response to json

### CODE REVIEW

**Comment by JacksonBates** [comment]
> how I can point to original repo, as I can only push to my repo(forked). I'm not allowed to push to original repo without being a contributor (which is not necessary). please help

Hmm, it must have been auto-generated somehow when you made your changes. You could just amend the package.json manually, I suppose?

**Comment by JacksonBates** [comment]
One last thing, once I merge this and update the article, how would you like to be credited?

Just a link to your github, or do you have a Twitter / insta / YouTube / Etsy shop you'd prefer to publicise?

**Comment by gskumawat0** [comment]
> > how I can point to original repo, as I can only push to my repo(forked). I'm not allowed to push to original repo without being a contributor (which is not necessary). please help
> 
> Hmm, it must have been auto-generated somehow when you made your changes. You could just amend the package.json manually, I suppose?

i think my github repo link will not reflect in original repo when you merge.

**Comment by gskumawat0** [comment]
> One last thing, once I merge this and update the article, how would you like to be credited?
> 
> Just a link to your github, or do you have a Twitter / insta / YouTube / Etsy shop you'd prefer to publicise?

Thank you jackson. i didn't thought of that much. i was going through your article and thought it can be improved. so i made a pr. you can add github(https://github.com/gskumawat0) and twitter(https://twitter.com/dev_gskumawat)

**Comment by JacksonBates** [comment]
Thanks. It's late here now, so I'll merge in the morning :)

**Pull request merged**
